version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Server123."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicioturismo
    ports:
      - "8001:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductDB;User=sa;Password=Server123.;Encrypt=False;TrustServerCertificate=True;
    networks:
      - backend

networks:
  backend:
    driver: bridge
